#!/usr/bin/env python3
"""Build a deterministic, progressively publishable Git and Flutter curriculum."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MAX_LESSONS = 250


# Each topic describes a real skill. Ten activity forms below revisit it through
# different kinds of practice, rather than generating ten numbered paraphrases.
TOPICS = [
    {"id": "git-worktree", "track": "Git", "title": "The working tree and repository", "summary": "Distinguish the files on disk, Git metadata, and the repository root.", "concept": "A repository is a working directory plus Git's database in .git. The working tree is the checked-out files you edit. Git status compares those files and the index with the current commit; it does not automatically save edits.", "scenario": "A teammate edits lib/cart.dart and creates notes/release.md, then asks why neither appears in the last commit.", "example": "Run `git rev-parse --show-toplevel` to find the repository root and `git status --short` to see working-tree changes. A leading `??` means an untracked path; ` M` means a tracked file differs from the index.", "pitfall": "A folder containing source files is not necessarily the repository root. Commands run from a nested directory still operate on its containing repository unless a different repository is found.", "terms": "repository root, working tree, .git, tracked, untracked"},
    {"id": "git-status", "track": "Git", "title": "Read status as a change map", "summary": "Interpret status output before staging or committing.", "concept": "`git status` describes differences in two columns: the first is the index compared with HEAD, and the second is the working tree compared with the index. `??` marks a path Git has not begun tracking.", "scenario": "A status report shows `M  lib/theme.dart`, ` M lib/home.dart`, and `?? scratch.txt`.", "example": "The theme change is staged; the home change is unstaged; scratch.txt is untracked. `git diff --cached` inspects the staged theme change, while `git diff` inspects the unstaged home change.", "pitfall": "The two status columns are easy to conflate. A staged change can coexist with later unstaged edits to the same file.", "terms": "HEAD, index, staged, unstaged, untracked"},
    {"id": "git-staging", "track": "Git", "title": "Stage precise changes", "summary": "Use the index to assemble a reviewable commit.", "concept": "The index (also called the staging area) is a proposed next snapshot. A commit records the index, not every file currently modified on disk. Stage by path, inspect the staged diff, and adjust until the snapshot is coherent.", "scenario": "You changed a login form and also added an unrelated debug print to a shared utility file.", "example": "`git add lib/login.dart` stages one path. `git diff --cached` reviews exactly what the next commit would contain. `git restore --staged lib/login.dart` removes it from the index without discarding the working copy.", "pitfall": "`git add .` may sweep unrelated files into a commit. Staging is reversible; committing is a separate action.", "terms": "index, git add, staged diff, restore --staged"},
    {"id": "git-diff", "track": "Git", "title": "Inspect diffs at the right boundary", "summary": "Compare working files, staged content, and commits.", "concept": "A diff is a comparison between two states. `git diff` compares working tree to index; `git diff --cached` compares index to HEAD; `git diff A..B` compares commit trees. The boundary determines which edits you see.", "scenario": "A reviewer says the feature looks complete, but you need to verify which exact changes would enter the commit.", "example": "Use `git diff --check` for whitespace problems, `git diff --cached -- lib/feature.dart` for the proposed committed version of one path, and `git diff HEAD` to see all tracked differences from the current commit.", "pitfall": "A clean `git diff` does not mean there are no changes: everything might already be staged.", "terms": "diff, unified hunk, index, HEAD, pathspec"},
    {"id": "git-commit", "track": "Git", "title": "Make useful commits", "summary": "Record coherent snapshots with messages that explain intent.", "concept": "A commit identifies a tree snapshot, its parent, metadata, and a message. Good commits group one understandable change and say why it exists; the staged index determines the tree.", "scenario": "You are splitting a settings-screen redesign from a formatting-only cleanup before handing work to a reviewer.", "example": "Stage only the redesign, inspect `git diff --cached`, then commit with a message such as `Add accessible settings theme controls`. A second cleanup can be staged and committed separately.", "pitfall": "A commit message like `updates` forces future readers to reconstruct intent from the diff. A commit does not include unstaged changes.", "terms": "snapshot, parent, commit message, atomic change"},
    {"id": "git-history", "track": "Git", "title": "Navigate commit history", "summary": "Read the graph and locate changes without confusing history with the working tree.", "concept": "Commits form a directed graph through parent references. `git log` walks ancestry; `--oneline --graph --decorate --all` gives a compact view of branches and references. A branch name points to a commit and advances as new commits are made.", "scenario": "A bug appeared after last week's UI work, and two feature branches have since diverged.", "example": "Use `git log --oneline --graph --decorate --all` to orient yourself, then `git show <commit>` to inspect one snapshot and message. `git log -- lib/search.dart` narrows history by path.", "pitfall": "The most recent commit is not always the most recent change to a particular file, and branch names move over time.", "terms": "commit graph, ancestry, branch reference, git show"},
    {"id": "git-branch", "track": "Git", "title": "Branches as movable pointers", "summary": "Create and switch lines of work while preserving committed snapshots.", "concept": "A branch is a named pointer to a commit, not a copy of all files. New commits on the checked-out branch advance that pointer. `git switch -c` creates and checks out a branch in one step.", "scenario": "You need to prototype a profile editor while keeping the main line ready for a small production fix.", "example": "Start with `git switch -c feature/profile-editor`. `git branch --show-current` confirms where commits will land. Switching branches changes the checked-out snapshot when Git can do so safely.", "pitfall": "Uncommitted edits are not stored on a branch pointer. Git may prevent a switch if those edits would be overwritten.", "terms": "branch, HEAD, switch, branch pointer"},
    {"id": "git-merge", "track": "Git", "title": "Merge compatible work", "summary": "Combine branch histories and recognize fast-forward and merge commits.", "concept": "Merging incorporates another branch's reachable commits. If the current branch is an ancestor of the other, Git can fast-forward its pointer. Diverged histories need a merge commit that has both tips as parents.", "scenario": "A validated color-contrast fix is ready to join the main branch after another independent copy update.", "example": "Switch to the destination branch and run `git merge fix/contrast`. Review the resulting status and history. A fast-forward needs no merge commit; diverged changes may produce one.", "pitfall": "Merging into the wrong checked-out branch changes the wrong line of work. Confirm `git branch --show-current` first.", "terms": "merge base, fast-forward, merge commit, destination branch"},
    {"id": "git-conflicts", "track": "Git", "title": "Resolve merge conflicts", "summary": "Use conflict markers and the three inputs to preserve intended behavior.", "concept": "A conflict means Git cannot automatically combine edits. Conflict markers delimit the current side (`HEAD`), the incoming side, and the shared base context. The correct resolution may combine, select, or rewrite both contributions.", "scenario": "Two branches change the same validation message: one improves plain language and the other adds a translation key.", "example": "Open the conflicted file, understand both versions, produce the intended final code without marker lines, run the relevant check, then `git add` the resolved path and complete the merge. `git merge --abort` returns to the pre-merge state if you need to restart.", "pitfall": "Choosing 'ours' or 'theirs' blindly can erase valid behavior. Markers left in source are syntax errors and semantic mistakes.", "terms": "conflict marker, ours, theirs, merge base, abort"},
    {"id": "git-remote", "track": "Git", "title": "Work with remotes", "summary": "Understand local branches, remote-tracking references, fetch, and push.", "concept": "A remote is a named connection such as `origin`. Fetch downloads objects and updates remote-tracking references like `origin/main`; it does not merge them into your current branch. Push publishes commits and updates a remote branch when permitted.", "scenario": "Your local feature branch is based on yesterday's main, while a teammate has pushed a new API contract.", "example": "`git fetch origin` refreshes remote-tracking refs. Inspect `git log --oneline HEAD..origin/main`, integrate intentionally, then push your branch. `git remote -v` shows configured destinations.", "pitfall": "A remote-tracking branch is a local record of observed remote state, not a live remote connection or your local branch.", "terms": "remote, fetch, remote-tracking branch, push, upstream"},
    {"id": "git-undo", "track": "Git", "title": "Choose the safe undo operation", "summary": "Restore files, unstage content, or reverse a published commit deliberately.", "concept": "Different undo commands affect different state. `restore` changes paths in the working tree or index; `reset` moves a branch pointer and may alter the index; `revert` creates a new commit that reverses an earlier commit.", "scenario": "A bad commit has already been pushed to a shared release branch and must be corrected without rewriting teammates' history.", "example": "Use `git revert <commit>` to record an inverse change on shared history. Use `git restore -- path` only when discarding that working-tree content is intended. Inspect status and diffs before destructive restoration.", "pitfall": "`reset --hard` discards staged and unstaged tracked edits. Rewriting a shared branch can disrupt collaborators.", "terms": "restore, reset, revert, shared history"},
    {"id": "git-ignore", "track": "Git", "title": "Keep generated and private files out", "summary": "Use ignore rules correctly and distinguish ignored files from tracked files.", "concept": "`.gitignore` patterns prevent matching untracked paths from being offered for tracking. They do not remove files already in Git's index. Specific patterns and directory rules make intent easier to audit.", "scenario": "A local Flutter build creates `.dart_tool/`, and a developer accidentally added a private signing configuration earlier.", "example": "Add an appropriate `.gitignore` pattern for generated output. `git check-ignore -v path` explains a matching rule. For a tracked file that should remain locally, remove it from the index with `git rm --cached path` and commit that change.", "pitfall": "Ignoring a tracked secret does not erase it from history or stop future commits from tracking it.", "terms": "pattern, negation, tracked file, git check-ignore"},
    {"id": "flutter-widget", "track": "Flutter", "title": "Compose a widget tree", "summary": "Model a screen as immutable widget descriptions composed from small pieces.", "concept": "Flutter builds UI from widgets arranged in a tree. A widget is an immutable configuration; elements and render objects manage identity, lifecycle, and layout behind it. Small widgets with clear inputs make screens easier to reason about.", "scenario": "A listing card needs a title, daily price, favorite button, and optional distance label.", "example": "Compose `Card` → `Padding` → `Column` and use `Row` for title and price. Extract a `ListingCard` widget with required listing data and an explicit favorite callback rather than reaching into unrelated global state.", "pitfall": "A widget is not the rendered pixel object and rebuilding a widget configuration is normal. Avoid enormous build methods with mixed responsibilities.", "terms": "widget, element, render object, composition, build"},
    {"id": "flutter-layout", "track": "Flutter", "title": "Reason about constraints and layout", "summary": "Diagnose overflow by following constraints from parent to child.", "concept": "Flutter layout is a one-pass conversation: constraints go down, sizes go up, and parents position children. A child must choose a size within its constraints. Flex widgets divide available main-axis space among children.", "scenario": "A narrow phone overflows when a long shop name shares a row with price and an action icon.", "example": "Wrap the flexible text in `Expanded` or `Flexible`, let it wrap or ellipsize intentionally, and keep the icon at a bounded size. Test the screen at narrow width and with long localized text.", "pitfall": "`Expanded` requires a bounded main-axis constraint. Putting it inside a scroll view with unbounded height can trigger a layout exception.", "terms": "BoxConstraints, bounded, main axis, Expanded, overflow"},
    {"id": "flutter-state", "track": "Flutter", "title": "Choose local state deliberately", "summary": "Use StatefulWidget for ephemeral state and keep updates inside lifecycle rules.", "concept": "State that belongs to one widget instance can live in `State<T>`. Calling `setState` synchronously marks that subtree for a rebuild; it should wrap the state change, not expensive asynchronous work. Durable or shared state needs an owner with appropriate lifetime.", "scenario": "A filter sheet has a temporary selected sort order and only applies it when the user presses Done.", "example": "Initialize draft selection in `initState`, update it inside `setState`, and return the chosen value when Done is tapped. Cancel simply closes the sheet without mutating the applied filter.", "pitfall": "Calling `setState` after disposal is invalid. Do not use a widget-local field for state that must survive navigation or be shared across screens.", "terms": "State object, setState, initState, dispose, ephemeral state"},
    {"id": "flutter-navigation", "track": "Flutter", "title": "Navigate with explicit route data", "summary": "Pass the minimum stable identifier and load destination data at the destination.", "concept": "Navigation changes which route is visible and may create a stack of pages. A route should have an explicit contract. Passing a stable ID often avoids stale copies and oversized route arguments; the destination can load current data and handle missing records.", "scenario": "A search result opens a shop detail page, and the listing might be edited before the user returns.", "example": "Navigate with `shopId`, load the latest shop record in the detail route, and represent loading, not-found, and error states. Define back behavior so filters and scroll position are preserved when expected.", "pitfall": "Passing a large mutable object hides data freshness assumptions. Unvalidated deep-link parameters can refer to missing or unauthorized records.", "terms": "route, Navigator, route argument, deep link, back stack"},
    {"id": "flutter-async", "track": "Flutter", "title": "Handle asynchronous UI states", "summary": "Represent loading, success, empty, and failure outcomes explicitly.", "concept": "Network and disk operations complete later. UI state should represent the pending operation and all meaningful results. Async callbacks need to respect widget lifetime; errors should be surfaced in a useful, recoverable way.", "scenario": "A chair search request can return results, no matches, a server error, or finish after the search screen closes.", "example": "Set loading before awaiting the repository, handle success and failure distinctly, and check `mounted` before updating disposed widget state. Prevent stale responses from an older query replacing newer results, for example with a request generation token.", "pitfall": "A spinner alone is not an error strategy. Catching every error and showing an empty list falsely tells users that the search succeeded with no matches.", "terms": "Future, await, loading, empty, error, mounted, stale response"},
    {"id": "flutter-lists", "track": "Flutter", "title": "Build efficient scrollable lists", "summary": "Use lazy list construction, stable identity, and deliberate empty/loading states.", "concept": "`ListView.builder` constructs visible children on demand, making it suitable for long or dynamic collections. Stable keys help Flutter preserve element identity when items move. Keep row work bounded and avoid rebuilding the whole dataset unnecessarily.", "scenario": "Search results reorder after favorites change, but each row contains an input-like control that should retain the correct state.", "example": "Provide a stable key derived from the listing ID, use `ListView.builder`, and render separate loading, empty, and populated states. If reorder animations or stateful rows are important, provide item identity to the sliver delegate.", "pitfall": "Index keys can attach state to the wrong item after insertions or reordering. Creating every row eagerly wastes work for large collections.", "terms": "ListView.builder, lazy, Key, identity, sliver"},
    {"id": "flutter-forms", "track": "Flutter", "title": "Validate forms with clear ownership", "summary": "Connect controllers, validators, submission, and cleanup into a predictable form flow.", "concept": "A `Form` groups fields and exposes validation through `FormState`. A `TextEditingController` gives explicit access to text and must be disposed by its owner. Validation should be timely, specific, and repeated at the trusted server boundary.", "scenario": "A chair request form requires start and end dates, a message length limit, and confirmation before submission.", "example": "Give the form a `GlobalKey<FormState>`, validate date ordering as well as required fields, disable duplicate submission while saving, and dispose controllers in the owning State. Keep server validation authoritative.", "pitfall": "Client-side validation improves feedback but cannot enforce authorization or guarantee the submitted data is valid.", "terms": "Form, FormState, validator, controller, dispose, server validation"},
    {"id": "flutter-theming", "track": "Flutter", "title": "Build consistent Material themes", "summary": "Centralize color, typography, and component defaults with theme extensions where needed.", "concept": "`ThemeData` provides inherited visual defaults. `ColorScheme` communicates semantic roles such as primary, surface, and error; component themes keep buttons, inputs, and cards consistent. Theme-aware widgets adapt when the app changes appearance.", "scenario": "The booking flow has hand-picked colors on each page and contrast becomes inconsistent in dark mode.", "example": "Define light and dark `ThemeData` from coherent color schemes, set shared component themes, and read colors through `Theme.of(context)`. Use a `ThemeExtension` for brand tokens not represented by Material roles.", "pitfall": "A raw brand color does not automatically have sufficient contrast or the right semantic meaning for every component.", "terms": "ThemeData, ColorScheme, component theme, ThemeExtension, contrast"},
    {"id": "flutter-accessibility", "track": "Flutter", "title": "Make controls accessible", "summary": "Provide meaningful labels, adequate targets, contrast, and non-color status cues.", "concept": "Accessible UI exposes purpose and state to assistive technology and remains usable with different input and visual conditions. Flutter semantics describe controls; touch targets and contrast matter even when the UI looks polished on one device.", "scenario": "A heart icon toggles a favorite, but currently has no text label and color is its only state signal.", "example": "Use an `IconButton` with a descriptive tooltip and semantic label, expose toggled state with an appropriate control, and keep the tap target comfortably sized. Verify that favorite and unfavorite are distinguishable without color alone.", "pitfall": "Wrapping everything in `Semantics` can duplicate announcements. Test actual focus and reading order instead of adding labels indiscriminately.", "terms": "Semantics, label, tooltip, target size, contrast, focus order"},
    {"id": "flutter-async-lifecycle", "track": "Flutter", "title": "Respect widget lifecycle", "summary": "Initialize and release resources at the correct lifecycle boundary.", "concept": "A State object can initialize controllers and subscriptions in `initState`, respond to changed widget inputs in `didUpdateWidget`, and release resources in `dispose`. Async work may outlive the State, so cancel or guard it.", "scenario": "A detail page listens to a live booking stream and also owns a scroll controller.", "example": "Create the controller and subscription with the State, cancel the subscription and dispose the controller in `dispose`, and replace the subscription if its booking ID changes in `didUpdateWidget`.", "pitfall": "Disposing shared resources owned by another object breaks that owner. Merely checking `mounted` prevents setState after disposal but may not cancel wasted work.", "terms": "initState, didUpdateWidget, dispose, subscription, ownership"},
    {"id": "flutter-data-model", "track": "Flutter", "title": "Model API data defensively", "summary": "Parse external JSON with explicit types, validation, and useful failure context.", "concept": "JSON is untrusted dynamic input. Convert it at the boundary into typed domain objects, validate required fields and formats, and keep serialization rules explicit. A failed parse should identify the field or record without leaking sensitive payloads.", "scenario": "An API returns a chair price as a number, an optional image URL, and an ISO date that may be absent in old records.", "example": "Write a `fromJson` factory that checks numeric types, handles nullable image URLs, parses dates deliberately, and documents a backward-compatible default only when the product contract defines one.", "pitfall": "Blind `as` casts crash at runtime and treating missing data as a plausible zero can misrepresent price or availability.", "terms": "JSON boundary, factory, nullability, serialization, validation"},
    {"id": "flutter-repository", "track": "Flutter", "title": "Separate UI from data access", "summary": "Use a repository boundary to make sources replaceable and screens testable.", "concept": "A repository gives the application a stable interface for loading and changing domain data, while hiding HTTP, caching, and parsing details. It lets widgets express user intent instead of constructing requests directly.", "scenario": "The listing screen currently builds URLs, parses response maps, and shows snackbars in one button callback.", "example": "Define a `ListingRepository` method such as `searchListings(filters)`, implement transport and parsing behind it, and inject the interface into the screen. Map repository outcomes to UI states in one place.", "pitfall": "A repository that merely renames every HTTP call without owning a useful boundary adds indirection but no clarity.", "terms": "repository, dependency injection, data source, domain model"},
    {"id": "flutter-testing", "track": "Flutter", "title": "Test widgets through user-visible behavior", "summary": "Arrange realistic dependencies and assert what a user can observe and do.", "concept": "Widget tests build a subtree in a test environment and interact through finders and gestures. Strong tests assert visible behavior and meaningful state transitions while substituting slow or external dependencies at a clear seam.", "scenario": "A favorite button should update its selected state and call the save action once, even after the row rebuilds.", "example": "Pump the widget with a fake repository, tap the labeled favorite control, pump the resulting frame, and assert its semantic selected state and one repository call. Add a rebuild to catch state tied to transient widget identity.", "pitfall": "Tests coupled to private implementation details fail during harmless refactors. A test that only checks a widget exists misses behavior.", "terms": "WidgetTester, finder, pump, fake dependency, semantics"},
]


ACTIVITIES = [
    ("spot-the-state", "Diagnose the state", "Read the scenario and label the exact state or boundary involved. Explain what the observation proves and what it does not prove."),
    ("predict-the-result", "Predict before acting", "Write down the expected outcome of the example command or code change. Include the state that should remain untouched."),
    ("guided-practice", "Perform a guided task", "Carry out the scenario as a small task. State the safe first inspection, the smallest useful action, and the evidence that confirms success."),
    ("debug-a-mistake", "Debug a realistic mistake", "A colleague makes the pitfall described below. Identify the mistaken assumption, the likely symptom, and the least disruptive recovery."),
    ("compare-two-choices", "Compare two approaches", "Compare the recommended approach with one plausible alternative. Choose based on this scenario's ownership, safety, and maintenance needs."),
    ("read-the-evidence", "Interpret evidence", "Use the example output or behavior as evidence. Describe what it establishes, what remains uncertain, and which next observation would reduce uncertainty."),
    ("design-a-check", "Design a verification check", "Create a short checklist or test for the scenario. It must catch the pitfall and assert user-visible or repository-visible behavior rather than implementation trivia."),
    ("modify-the-example", "Adapt the worked example", "Change the scenario in one concrete way and adapt the example. Explain how the new constraint changes the command, widget structure, or state handling."),
    ("recover-safely", "Plan a safe recovery", "Assume the operation is interrupted or the first attempt fails. Write a recovery sequence that preserves valuable work and confirms the final state."),
    ("teach-back", "Teach it back", "Explain the idea to a teammate in your own words, then give one specific rule of thumb and one case where that rule needs an exception."),
]


def slug(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def lessons() -> list[dict[str, str]]:
    result = []
    for topic_number, topic in enumerate(TOPICS, start=1):
        for stage_number, (stage, activity_title, instruction) in enumerate(ACTIVITIES, start=1):
            number = (topic_number - 1) * len(ACTIVITIES) + stage_number
            lesson_id = f"{number:03d}-{topic['id']}-{stage}"
            title = f"{topic['title']}: {activity_title}"
            body = (
                f"## Learning goal\n\n{topic['summary']}\n\n"
                f"## How it works\n\n{topic['concept']}\n\n"
                f"## Worked example\n\n{topic['example']}\n\n"
                f"## Watch for\n\n{topic['pitfall']}\n\n"
                f"## Key terms\n\n{topic['terms']}\n\n"
                f"## Practice context\n\n{topic['scenario']}"
            )
            exercise = (
                f"{instruction}\n\nScenario: {topic['scenario']}\n\n"
                f"Use this concept: {topic['concept']}\n\n"
                f"A strong answer names a concrete action, the expected evidence, and how it avoids this pitfall: {topic['pitfall']}"
            )
            result.append({
                "id": lesson_id,
                "title": title,
                "topic": topic["track"],
                "summary": topic["summary"],
                "body": body,
                "exercise": exercise,
            })
    return result


def write_curriculum(count: int) -> None:
    selected = lessons()[:count]
    index_path = ROOT / "assets" / "lessons" / "index.json"
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(json.dumps(selected, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")

    lesson_dir = ROOT / "docs" / "lessons"
    if selected:
        lesson_dir.mkdir(parents=True, exist_ok=True)
        for lesson in selected:
            content = (
                f"# {lesson['title']}\n\n"
                f"**Topic:** {lesson['topic']}  \n"
                f"**Summary:** {lesson['summary']}\n\n"
                f"{lesson['body']}\n\n## Exercise\n\n{lesson['exercise']}\n"
            )
            (lesson_dir / f"{lesson['id']}.md").write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--count", type=int, default=MAX_LESSONS, help="number of ordered lessons to generate (0..250)")
    args = parser.parse_args()
    if not 0 <= args.count <= MAX_LESSONS:
        parser.error(f"--count must be between 0 and {MAX_LESSONS}")
    if len(TOPICS) != 25 or len(ACTIVITIES) != 10:
        raise RuntimeError("The curriculum must contain exactly 25 topics and 10 activities per topic")
    write_curriculum(args.count)


if __name__ == "__main__":
    main()
